CREATE DATABASE UserRegisterDB

IF NOT EXISTS (SELECT
			*
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE table_name = 'Client')
BEGIN
	CREATE TABLE Client (
		Id INT NOT NULL IDENTITY
	   ,Name VARCHAR(250) NOT NULL
	   ,CPF VARCHAR(11) NOT NULL
	   ,Email VARCHAR(200) NOT NULL
	   ,Phone VARCHAR(11) NOT NULL
	   ,Active BIT NOT NULL
	   ,DateRegister DATETIME NOT NULL DEFAULT GETDATE()
	)
END;